if: commit_message !~ /travis build/
language: python
python:
  - 3.7
node_js:
  - 10
git:
  depth: 5
services:
  - docker
branches:
  only:
    - master
env:
  - NODE_OPTIONS="--max_old_space_size=4096"
install:
  - bash build.sh install
script:
  - bash build.sh package
deploy:
  skip_cleanup: true
  provider: script
  script: bash build.sh deploy
