language: python
python:
  - 3.6
node_js:
  - 10
git:
  depth: 5
services:
  - docker
branches:
  only:
    - master
install:
  - python -m pip install --upgrade pip
  - pip install flake8
  - pip install wheel

jobs:
  include:
    - stage: app-build
      before_script:
        - export NODE_OPTIONS=–max_old_space_size=4096
      script:
        - cd trails-viz-app
        - npm install
        - npm run lint
        - npm run build
        - cd ..
    - stage: api-build
      script:
        - cd trails-viz-api
        - pip install -r requirements.txt
        - flake8 . --count --max-line-length=119 --exclude trailsvizapi/__init__.py --show-source --statistics
        - python setup.py bdist_wheel
        - cd ..

stages:
  - app-build
  - api-build
