name: trails_viz_api
channels:
  - defaults
dependencies:
  - python=3.7.16
  - pip
  - pip:
      - Flask==2.1.0
      - Werkzeug==2.0.0
      - jinja2==3.0.3
      - numpy==1.16.4
      - pandas==0.25.1
      - geopandas==0.4.1
      - flask-cors==3.0.8
      - Flask-Bcrypt==0.7.1
      - google-api-core==1.15.0
      - google-auth==1.10.0
      - google-cloud-core==1.1.0
      - google-cloud-storage==1.20.0
      - cryptography==3.2
      - urllib3==1.26.6
variables:
  FLASK_APP: trailsvizapi
  FLASK_ENV: development
