name: trails_viz_api
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.12.31
  - certifi=2022.12.7
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=22.3.1
  - python=3.7.16
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.38.4
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - attrs==24.2.0
      - bcrypt==4.2.1
      - cachetools==4.2.4
      - cffi==1.15.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cryptography==3.2
      - fiona==1.9.6
      - flask==2.1.0
      - flask-bcrypt==0.7.1
      - flask-cors==3.0.8
      - geopandas==0.4.1
      - google-api-core==1.15.0
      - google-auth==1.10.0
      - google-cloud-core==1.1.0
      - google-cloud-storage==1.20.0
      - google-resumable-media==0.4.1
      - googleapis-common-protos==1.66.0
      - idna==3.10
      - importlib-metadata==6.7.0
      - itsdangerous==2.1.2
      - jinja2==3.0.3
      - markupsafe==2.1.5
      - numpy==1.16.4
      - pandas==0.25.1
      - protobuf==4.24.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pyproj==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - requests==2.31.0
      - rsa==4.0
      - shapely==2.0.7
      - six==1.17.0
      - typing-extensions==4.7.1
      - urllib3==1.26.6
      - werkzeug==2.0.0
      - zipp==3.15.0
variables:
  FLASK_APP: trailsvizapi
  FLASK_ENV: development
  